export const CREATE_CAR = 'CREATE_CAR';
export const UPDATE_CAR = 'UPDATE_CAR';
export const DELETE_CAR = 'DELETE_CAR';
export const FETCH_ALL_CARS = 'FETCH_ALL_CARS';
export const FETCH_FILTER_CARS = 'FETCH_FILTER_CARS';
export const SET_EDITING_CAR = 'SET_EDITING_CAR';

export const CREATE_COMPANY = 'CREATE_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const FETCH_ALL_COMPANIES = 'FETCH_ALL_COMPANIES';
export const SET_EDITING_COMPANY = 'SET_EDITING_COMPANY';

export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const SET_EDITING_USER = 'SET_EDITING_USER';


export const LOGIN = 'LOGIN';
export const LOG_OUT = 'LOG_OUT';
