version: '2'
services:
  database:
    image: mysql:5.6
    container_name: car_catalog
    command:
      [
        '--default-authentication-plugin=mysql_native_password',
        '--default-time-zone=-07:00',
      ]
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_catalog
      MYSQL_USER: catalog_user
      MYSQL_PASSWORD: b0ou&CRWGMklvxqy1VAUo@C^Lj6ZaF
